export const ADMIN_OPERATIONS = [
  'providers.list',
  'apiKeys.list',
  'apiKeys.create',
  'apiKeys.update',
  'apiKeys.revoke',
  'authManagers.list',
  'authManagers.create',
  'authManagers.delete',
  'authManagers.credentials.list',
  'profiles.list',
  'profiles.create',
  'profiles.update',
  'profiles.delete',
  'profiles.availability.cached',
  'profiles.availability.refresh',
  'profiles.mobileSuica.login.start',
  'profiles.mobileSuica.login.complete',
  'assets.valuations.latest',
  'history.sync',
  'jobs.list',
] as const
